// DestinationV.UI/src/app/routes/components/route-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { getRoutes, RouteState } from '../store/reducers';
import { RouteDto } from '../dtos/route.dto';
import { Observable } from 'rxjs';
import { LoadRoutes } from '../store/actions/routes.action';
import { take, tap } from 'rxjs/operators';
import { GlobalState, getPlaces } from 'src/app/store/reducers';
import { PlaceDto } from 'src/app/common/dtos/place.dto';
import { LoadPlaces } from 'src/app/store/actions/places.action';

@Component({
  selector: 'destinationv-route-list',
  templateUrl: 'route-list.component.html',
  styleUrls: ['./route-list.component.scss']
})
export class RouteListComponent implements OnInit {
  currentPanelId: string;
  routeList$: Observable<RouteDto[]>;
  placesList$: Observable<PlaceDto[]>;

  constructor(
    private store: Store<RouteState>,
    private storeGlobal: Store<GlobalState>,) {
    store.dispatch(new LoadRoutes());

    this.routeList$ = store.select(getRoutes);
    this.placesList$ = storeGlobal.select(getPlaces).pipe(
      tap(places => {
        if (!places || places.length === 0) {
          storeGlobal.dispatch(new LoadPlaces());
        }
      })
    );
  }

  setExpandedPanelId(routeId: string) {
    this.currentPanelId = this.currentPanelId === routeId ? null : routeId;
  }

  ngOnInit() {}
}

<div class="container-fluid">
  <h2>Routes</h2>

  <mat-accordion>
      <mat-expansion-panel *ngFor="let route of (routeList$ | async)"
      [expanded]="currentPanelId === route.id"
      disabled
      hideToggle>
      <mat-expansion-panel-header>
          <mat-panel-title>
                  <div class="col-md-3 align-self-center" data-testId="routeOrigin">
                    Origin: <strong>{{ route.origin.name }}</strong>
                  </div>
                  <div class="col-md-3 align-self-center" data-testId="routeDestination">
                    Destination: <strong>{{ route.destination.name }}</strong>
                  </div>
                  <div class="col-md-4 align-self-center" data-testId="routeDate">
                    Departing time: {{ route.departUtc | uDate: 'dd/MM/yyyy HH:mm' }}
                  </div>
                  <div class="col-md-2 align-self-center">
                    <button data-testId="buttonEdit" mat-mini-fab color="primary" (click)="setExpandedPanelId(route.id)"><mat-icon>edit</mat-icon></button>
                  </div>
          </mat-panel-title>
        </mat-expansion-panel-header>
        <destinationv-route-item [route]="route" [places]="placesList$ | async" (result)="actionOnResult($event)"></destinationv-route-item>
      </mat-expansion-panel>
  </mat-accordion>
</div>

// DestinationV.UI-React/src/routes-module/components/route-list/RouteList.tsx
import './RouteList.scss';
import { RouteDto } from '../../dto/route.dto';
import * as React from 'react';
import { connect } from 'react-redux';
import { loadRoutes, deleteRoute } from '../../store/action/route.action';
import { RouteItem } from './RouteItem';
import { PlaceDto } from '../../dto/place.dto';
import { ajax } from 'rxjs/ajax';
import { map, publishReplay, refCount } from 'rxjs/operators';
import { Observable } from 'rxjs';

import ExpansionPanel from '@material-ui/core/ExpansionPanel';
import ExpansionPanelSummary from '@material-ui/core/ExpansionPanelSummary';
import ExpansionPanelDetails from '@material-ui/core/ExpansionPanelDetails';
import { withStyles, createStyles, WithStyles } from '@material-ui/core/styles';
import { Fab, Typography, Icon } from '@material-ui/core';
import EditIcon from '@material-ui/icons/Edit';

const styles = (theme: any) =>
    createStyles({
        typeWhite: {
            color: 'white'
        }
    });

// const test = { [className in keyof typeof styles]: string };
// type ClassNames = { classes: test };

export interface ComponentProps extends WithStyles<typeof styles> {
    routes: RouteDto[];
    loadRoutes: Function;
    deleteProduct: (id: string) => void;
}

export class RouteList extends React.Component<ComponentProps, { currentPanelId: string }> {
    placeDto$: Observable<PlaceDto[]>;

    constructor(props: ComponentProps) {
        super(props);
        this.state = {
            currentPanelId: ''
        };
        this.delProd = this.delProd.bind(this);
        this.handleStateChange = this.handleStateChange.bind(this);
    }

    componentDidMount() {
        this.getData();
    }

    getData() {
        this.props.loadRoutes();
    }

    private requestPlaces(): Observable<PlaceDto[]> {
        // TODO: refactor this to either use redux or at least constants for the URL
        return ajax
            .getJSON('http://localhost:5000/api/place')
            .pipe(map(result => result as PlaceDto[]));
    }

    getPlaces(): Observable<PlaceDto[]> {
        // cache strategy to avoid multiple server call when loading ref objects
        if (!this.placeDto$) {
            this.placeDto$ = this.requestPlaces().pipe(
                publishReplay(1),
                refCount()
            );
        }
        return this.placeDto$;
    }

    delProd(id: string) {
        this.props.deleteProduct(id);
    }

    handleStateChange(panelId: string) {
        const that = this;

        return function() {
            that.setState({ currentPanelId: panelId });
        };
    }

    render() {
        if (this.props.routes) {
            return (
                <div className="container-fluid">
                    {this.props.routes.map((result, index) => {
                        return result ? (
                            <ExpansionPanel
                                expanded={this.state.currentPanelId === result.id}
                                key={'eps' + index}
                                square
                            >
                                <ExpansionPanelSummary>
                                    <div
                                        className={
                                            'col-md-3 align-self-center ' +
                                            this.props.classes.typeWhite
                                        }
                                        data-testid="routeOrigin"
                                    >
                                        Origin: <strong>{result.origin.name}</strong>
                                    </div>
                                    <div
                                        className={
                                            'col-md-3 align-self-center ' +
                                            this.props.classes.typeWhite
                                        }
                                        data-testid="routeDestination"
                                    >
                                        Destination: <strong>{result.destination.name}</strong>
                                    </div>
                                    <div
                                        className={
                                            'col-md-4 align-self-center ' +
                                            this.props.classes.typeWhite
                                        }
                                        data-testid="routeDate"
                                    >
                                        Departing time: {result.departUtc}
                                    </div>
                                    <div
                                        className={
                                            'col-md-2 align-self-center ' +
                                            this.props.classes.typeWhite
                                        }
                                    >
                                        <Fab
                                            color="primary"
                                            data-testid="buttonEdit"
                                            onClick={this.handleStateChange(result.id)}
                                        >
                                            <EditIcon />
                                        </Fab>
                                    </div>
                                </ExpansionPanelSummary>
                            </ExpansionPanel>
                        ) : null;
                    })}
                </div>
                // <div className="col-md-12">
                //     {this.props.routes.map((result, index) => {
                //         return result
                //             ? ([<div className="row" key={'row' + index}>
                //                 <RouteItem key={`elem${index}`} route={result} onDelete={this.delProd} places={this.getPlaces()} />
                //             </div>,
                //             <div key={'emp-row' + index} className="row">&nbsp;</div>])
                //             : null;
                //     })}
                // </div>
            );
        } else {
            return null;
        }
    }
}

interface OwnProps {}

const mapStateToProps = (state: any) => ({
    routes: state.routes
});

const mapDispatchToProps = (dispatch: Function, props: OwnProps) => ({
    loadRoutes: () => dispatch(loadRoutes()),
    deleteProduct: (id: string) => dispatch(deleteRoute(id))
});

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(withStyles(styles)(RouteList));
